# CI for openseaChest through Travis CI
language: c

branches:
  only:
  - master
  - develop
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
matrix:
  include:
  - os: linux
    sudo: false
    compiler: clang
    dist: xenial
    script: make
  - os: linux
    sudo: false
    compiler: gcc
    dist: xenial
    script: make
